site_name: ðŸ§¬ Ruck Docs
repo_url: https://github.com/nmichlo/ruck
repo_name: nmichlo/ruck
theme:
  name: material
  palette:
    scheme: default
    primary: green
  icon:
    repo: fontawesome/brands/github
    logo: material/library
  favicon: images/favicon.png
plugins:
  - search
  - mkdocstrings # reference functions and code in markdown `::: module.class.func`
  - git-revision-date-localized: # visible last edit date on each page
      type: date
      fallback_to_build_date: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
# THE !! CURRENTLY BREAKS READTHEDOCS
# https://github.com/readthedocs/readthedocs.org/issues/7865
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
